### ISSUE TITLE
Mate Applet

### ISSUE THREAD

**Issue by dvrhax** [M7S/dockbarx#24]
I'd like to assist in getting dockbarx working in mate again.  Currently I use dockx and a bastardized toolbar setup so that they are kind of integrated. However I would really love for applet panel to work again and clean everything up.  If someone understands where the issue is and point me in a good direction to start I'd love to take a crack at fixing it.  From what I gather it has something to do with mate dropping the python applet api so the next question would be would it be easier to reimplement the python api in mate or modify dockbarx to work with whatever system mate is using now.

Thanks

**Comment by Isakku** [comment]
Wondering the same here. By what I remember, the last error I got said that python-gnomeapplet required python version < 2.7 and that my Linux mint mate 17.3 had 2.7.5 installed or something like that.  I'm wondering if it could be possible to redo that part of the code without using that pesky python-gnomeapplet. If that's not possible, I wonder if it would be possible to update the python-gnomeapplet package to work with python  2.7.5.

**Comment by kq01526** [comment]
@dvrhax and @Isakku :

Since dockbarx does no longer seem to be actively maintained (assuming from the commit history), maybe you might want to have a look at the MATE dock-applet:

https://github.com/robint99/dock-applet
http://www.webupd8.org/2015/05/dock-applet-icon-only-window-list-for.html

:wink:

**Comment by M7S** [comment]
I haven't made a conscious decision to stop developing DockbarX, even if I have been extremely inactive the last two years. I hope to do a better job in the future.

But porting to PyGObject is quite hard. I got stuck on it so many times two years ago that I gave up (and lost quite a bit of my interest in developing DockbarX, as you can see). So for now I make no promises regarding DockbarX in gnome-panel or mate-panel.

**Comment by Isakku** [comment]
Hey @M7S ! Glad to hear from you! 
How about this? https://github.com/M7S/dockbarx/tree/pygi-migration it seems someone has already worked on a PyGObject branch for your project. 

Even though I am a programmer, I don't have much experience withy Python, and since I mostly program for windows and for web there are things I don't understand. 

I have downloaded the code from that branch and compared it with the main project and it seems to have been completely ported but I think the panel dockbarx_factory file still relies on python-gnomeapplet because it has a line that says "import gnomeapplet". I have also followed @kq01526 's hint and installed that MATE dock-applet, which does work, but not quite as I expected, It simply adds  application grouped buttons to the panel instead of replacing the current buttons with application grouped ones... now I have two buttons ... pff... 
I have checked that applet code and even though it's coded in python too, it is very different from your code... *SIGH* 

Long short story, I would like to help but there's still much I must learn about the linux system, specially the MATE desktop for which I want this to work.

**Comment by M7S** [comment]
Hi!
That's my branch. It was my latest try. I was working on getting the standalone dock to work with PyGObject (and gtk3) before looking into the gnomeapplet.

**Comment by Isakku** [comment]
@M7S Oh sorry, I didn't notice. Perhaps you could help me help you. I have installed IDLE, but I don't know how to test changes nor if those will work at all. Could you please tell me what tools you used to develop dockbarx and how to compile / test the code?

**Comment by kq01526** [comment]
> @Isakku wrote:
> 
> I have also followed @kq01526 's hint and installed that MATE dock-applet, which does work, but not quite as I expected, It simply adds application grouped buttons to the panel instead of replacing the current buttons with application grouped ones... now I have two buttons ... pff... 

That is not true. You must have done something wrong. The [mate-dock-applet](https://github.com/robint99/dock-applet) from @robint99 works just fine and does not have the issue you claim it would have. You probably did not set up your panels properly.

Just have a look at the following video, beginning at around the 13:35 min mark, it shows the "Mutiny" layout featuring the [mate-dock-applet](https://github.com/robint99/dock-applet) from @robint99:

https://youtu.be/w68iwj0eHQ0

:wink:

Anyway, good to see that you are back @M7S :smiley: . Hoping that dockbarx will flourish again :+1: .

Regards

**Comment by kq01526** [comment]
PS: Had the wrong video link in the previous post. Updated now.

**Comment by Isakku** [comment]
@kq01526 thank you!
>   You probably did not set up your panels properly.
hmm... perhaps. 
All I know is that since I'm using Linux Mint Mate 17.3 I followed the instructions stated here:
https://github.com/robint99/dock-applet/blob/master/README.md
in the "Other distributions" section 
and then right clicked the pannel and added the dock-applet. I think I will post a bug report with a screenshot.
Yet, I would still like to see dockbarx working because it has thumbnail preview and dock-applet lacks such feature.

**Comment by kq01526** [comment]
> @Isakku wrote:
> 
> hmm... perhaps. 

See:

https://github.com/robint99/dock-applet/issues/51

> @Isakku wrote:
> 
> Yet, I would still like to see dockbarx working because it has thumbnail preview and dock-applet lacks such feature.

See:

https://github.com/robint99/dock-applet/issues/49

Regards

**Comment by M7S** [comment]
Since the gtk3 port is working now and mate is getting support for gtk3 panel applets, I hope to be able to have a mate applet for dockbarx done (or in beta phase) before ubuntu mate 16.10 is released. (It's just my goal, though, not a promise. My private life is pretty busy right now.)

**Comment by M7S** [comment]
Works now.
