### ISSUE TITLE
Dockbarx doesn't work on 16.04

### ISSUE THREAD

**Issue by JanFrydrych** [M7S/dockbarx#27]
Dockbarx xfce panel plugin doesn’t work on my Ubuntu Studio 16.04. I was using Xuzhen fork installed manually on 15.10. Everything was working perfectly. After the update to 16.04 xfce panel plugin has stopped working, but I was able to enter dockbarx preferences. I added Xuzhen ppa and installed dockbarx from this ppa. It didn't help. Finally, I removed Xuzhen ppa, uninstalled fork and added official ppa. Today I’ve installed the newest version from official ppa and it still doesn’t work. The only change is that now dockbarx preferences doesn’t work as well. I would be grateful for any suggestions.

**Comment by M7S** [comment]
If you have installed anything manually, those files will be used even if you install from a ppa later. Manual installs install in /usr/local/lib while the ppas installs the files in /usr/lib and the former is used over the later.

If you want to use the ppa instead of manual install you need to delete the files that the manual install made. Run the manual install again and see where it puts the files and remove them. Unfortunately there's no uninstall options in the setup system that Dockbarx uses.

**Comment by JanFrydrych** [comment]
Thank you very much for your help and work. Dockbarx is great :). I have deleted old version files and everything works perfectly just like before. 
I have got one more question. I have noticed that some applications in 16.04 have new labels (names) in Polish translation. For example “Thunar” is now something like: “Open a folder with the help of file manager Thunar”. So now Thunar window list in dockbarx xfce plugin is quite wide because of this very long title. It is irritating because close buttons are far away from Thunar icon. Do you know where can I find this “Open a folder with the help of file manager Thunar” label and change it to “Thunar”?

**Comment by M7S** [comment]
You can right click the launcher in DockbarX and choose preferences (or is it properties?) and choose edit launcher and choose a name of your liking.
