### ISSUE TITLE
Won't work on Wayland

### ISSUE THREAD

**Issue by tliron** [M7S/dockbarx#34]
It seems that DockbarX makes a few calls to X11 that won't work on Wayland.

I wonder if these calls are really necessary? Or perhaps they are not supported in XWayland?

**Comment by M7S** [comment]
I guess that at least keyboard shortcuts depends on calls to X11. I have to look into this when I've got time.

You are using the regular dockbarx, right? I would be interested in knowing if the same problems exist in the gtk3 branch.

**Comment by tliron** [comment]
I am running DockX 0.9.2 in Ubuntu GNOME.

How would I test the GTK3 branch? Would be happy to test for you.

**Comment by kq01526** [comment]
> @tliron wrote:
> How would I test the GTK3 branch? Would be happy to test for you.

With "gtk3 branch", @M7S probably is referring to this:

https://github.com/M7S/dockbarx/tree/pygi-migration

However, @hotice (Andrew from WebUpd8) does not have this included in the [dockbar-main PPA](https://launchpad.net/~dockbar-main/+archive/ubuntu/ppa).

Maybe @hotice and @M7S could add an additional "dockbar-unstable" PPA to https://launchpad.net/~dockbar-main which would be based on the development branch of DockbarX?

Regards

**Comment by hotice** [comment]
I maintain the DockBarX PPA, but I can't create a new PPA for the Dockbar-main group, @M7S needs to create it. If he does, I'll try to package the GTK3 branch when I have some free time.

**Comment by tliron** [comment]
I hope this issue hasn't been forgotten. My love for DockbarX is the last holdout for me from switching to Wayland. :)

**Comment by tliron** [comment]
Hooray, I found a workaround! Run this command before DockX:
`touch ~/.Xauthority`

**Comment by kq01526** [comment]
@tliron You might want to reconsider your setup. You said you're running Ubuntu GNOME with DockX. Instead of doing that, you could simply run KDE Plasma 5 (i.e. Kubuntu or even better KDE neon).

You can actually configure the task manager in the Plasma 5 panel to work like DockbarX/DockX. Plasma 5 has this functionality built-in, no need to add anything. And it even has window thumbnail previews.

Just saying, since DockbarX does no longer seem to be actively maintained and Plasma 5 works really well in that regard.
