### ISSUE TITLE
Display labels instead of icons

### ISSUE THREAD

**Issue by insertt** [M7S/dockbarx#48]
It would be cool if DockBarX would support displaying opened application labels instead of icons (as option in configuration, of course), ex.:
![image](https://user-images.githubusercontent.com/25823411/32065102-09cb538a-ba7c-11e7-8975-026027192508.png)

**Comment by M7S** [comment]
I believe it's less productive since the buttons would have to move around to make room for the text. My goal with DockbarX is that if you for example want to interact with Firefox through Dockbarx you should be able to do that from the same few pixels on the screen at all time (as long as Firefox is a pinned application of course.

tl;dr I have no interest in implementing this. Sorry.
