### ISSUE TITLE
xfce4-dockbarx-plugin suddenly missing

### ISSUE THREAD

**Issue by agasigp** [M7S/dockbarx#95]
After upgraded to Linux Mint Tricia, my dockbarx plugin is missing. I can't find it anymore on plugin. The dockbarx is also missing/disappear from the panel applet. Tried to reinstall it but it's not working. Any solution for that?
![Screenshot_2019-12-24_18-26-13](https://user-images.githubusercontent.com/2476867/71411171-ea7abf80-267a-11ea-948b-cce5249aac5e.png)
![Screenshot_2019-12-24_18-21-06](https://user-images.githubusercontent.com/2476867/71411174-ea7abf80-267a-11ea-89b8-2e57f7fc8d3f.png)

**Comment by xuzhen** [comment]
The version of xfce4-panel in Linux Mint Tricia is 4.14.1, which is newer than the one in Ubuntu 18.04.3. Since the packages in my PPA were built for Ubuntu only, they are not compatible with Linux Mint Tricia. Thus, the xfce4-dockbarx-plugin package was automatically removed during the upgrade.

Luckily, the binary files in xfce4-dockbarx-plugin still work on Linux Mint Tricia. you only need to modify the dependency information in the affected package.
```
cd /tmp/
apt-get download xfce4-dockbarx-plugin
mkdir xfce4-dockbarx-plugin
dpkg-deb -x xfce4-dockbarx-plugin_0.4.1+git20160817-1~bionic1_*.deb xfce4-dockbarx-plugin
dpkg-deb -e xfce4-dockbarx-plugin_0.4.1+git20160817-1~bionic1_*.deb xfce4-dockbarx-plugin/DEBIAN
sed -i 's/bionic1/bionic1.1/;s/4\.13/4.15/' xfce4-dockbarx-plugin/DEBIAN/control
dpkg-deb -b xfce4-dockbarx-plugin
sudo apt install /tmp/xfce4-dockbarx-plugin.deb
```
